mutation updateProduct($id: ID!, $name: String, $cost: Int, $amountAvailable: Int) {
  updateProduct(id: $id, name: $name, cost: $cost, amountAvailable: $amountAvailable) {
    id
    name,
    cost,
    amountAvailable
  }
}
