mutation createProduct($name: String!, $cost: Int!, $amountAvailable: Int) {
  createProduct(name: $name, cost: $cost, amountAvailable: $amountAvailable) {
    id
    name,
    cost,
    amountAvailable
  }
}
