#import "./login-register-fragment.gql"

mutation forgottenPasswordReset($token: String!, $password: String!) {
  reset: forgottenPasswordReset_v1(token: $token, password: $password) {
    ...loginRegisterFragment
  }
}