mutation removeFromRoleOnUser($id1: ID!, $id2: ID!) {
  removeRoleFromUser(rolesUserRoleId: $id1, rolesUserId: $id2) {
    rolesUserRole {
      id
    }
    usersUser {
      id
    }
  }
}
